name: Lint

on:
  push:
    branches: [ master, for-master ]
  pull_request:
    branches: [ master, for-master ]

jobs:
  lint-c:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: "checkout submodules"
        run: |
         git submodule set-url external/busybox/upstream https://github.com/mirror/busybox
         git submodule update --init --recursive

      - name: "install tools"
        run: |
         sudo apt-get -y -qq install \
          gcc make automake autoconf pkg-config udev help2man \
          libkmod-dev libz-dev libbz2-dev liblzma-dev \
          libzstd-dev libelf-dev libtirpc-dev libcrypt-dev
         sudo apt-get -y -qq install astyle

      - name: "configure"
        run: |
         ./autogen.sh
         ./configure

      - name: "prepare gittree"
        run: |
         git config --global user.email "ci@example.com"
         git config --global user.name "GitHubCI commiter"
         git commit -a -m 'CI: update git tree'

      - name: "indent"
        run: |
         make indent-c

      - name: "check formatting"
        run: |
         git diff --exit-code

  lint-shell:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: "checkout submodules"
        run: |
         git submodule set-url external/busybox/upstream https://github.com/mirror/busybox
         git submodule update --init --recursive

      - name: "install tools"
        run: |
         sudo apt-get -y -qq install \
          gcc make automake autoconf pkg-config udev help2man \
          libkmod-dev libz-dev libbz2-dev liblzma-dev \
          libzstd-dev libelf-dev libtirpc-dev libcrypt-dev
         sudo apt-get -y -qq install shellcheck

      - name: "configure"
        run: |
         ./autogen.sh
         ./configure

      - name: "shellcheck"
        run: |
         make verify

  unittests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: "checkout submodules"
        run: |
         git submodule set-url external/busybox/upstream https://github.com/mirror/busybox
         git submodule update --init --recursive

      - name: "install tools"
        run: |
         sudo apt-get -y -qq install \
          gcc make automake autoconf pkg-config udev help2man \
          libkmod-dev libz-dev libbz2-dev liblzma-dev \
          libzstd-dev libelf-dev libtirpc-dev libcrypt-dev
         sudo apt-get -y -qq install shellcheck

      - name: "configure"
        run: |
         ./autogen.sh
         ./configure

      - name: "build"
        run: |
         make

      - name: "unittests"
        run: |
         export PATH="$PWD/external/libshell/upstream:$PATH"
         make check
